name: check-tool
on:
  workflow_dispatch:
jobs:
  tortellini:
    runs-on: ubuntu-latest
    steps:
      - name: tortellini-action
        uses: tortellini-tools/action@v3
        
          
            
