name: check-tool
on:
  workflow_dispatch:
jobs:
  tortellini:
    runs-on: ubuntu-latest
    steps:
      - name: tortellini-action
      - uses: actions/checkout@v2
      - uses: tortellini-tools/action@v3
      - uses: actions/upload-artifact@v2
        with:
          name: tortellini-result
          path: .tortellini/out
        
          
            
