name: Create Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
         
      - name: Update config.json with new version
        run: |
          VERSION=${{ github.ref }}
          VERSION=${VERSION#v}

          # Update the version field using jq
          jq --arg v "$VERSION" '.general.version = $v' config.json > config.json.tmp && mv config.json.tmp config.json
          
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add config.json
          git commit -m "update config.json to version $VERSION"
          git push origin main
    
      - name: Create release from tag
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          prerelease: false
          draft: false
